-- Table 'utilisateur'

DROP TABLE  IF EXISTS UTILISATEUR;
CREATE TABLE UTILISATEUR  (
    ID_UTILISATEUR bigint(20) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    COMPTE_ACTIVE bit(1) NOT NULL,
    ID_TALIBE bigint(20) NOT NULL,
    PRIMARY KEY (ID_UTILISATEUR)
)ENGINE=InnoDB;
ALTER TABLE UTILISATEUR
ADD CONSTRAINT fk_talibe_utilisateur FOREIGN KEY (id_talibe) REFERENCES talibe(id_talibe);
